version: 0.2

phases:
  build:
    commands:
      - echo "Build started at `date`"
      - mvn -B clean package
      - echo "Build completed at `date`"
artifacts:
  files:
    - - '**/*'
  name: AppBuildArtifacts
