version: 0.2

phases:
  build:
    commands:
      - echo "Build started at `date`"
      - mvn -B clean package
      - echo "Build completed at `date`"
      - echo "Webhook Event ${CODEBUILD_WEBHOOK_TRIGGER}"
      - . target/demoapp.properties
      - echo "Application version ${PROJECT_VERSION}"
artifacts:
  files:
    - '**/*'
  name: AppBuildArtifacts
